export interface BookSubject {
  name: string;
  description: string;
  pages: string;
  size: string;
  image: string;
  pdf: string;
}

export interface BookGrade {
  grade: number;
  accent: string;
  description: string;
  subjects: BookSubject[];
}

export const booksByGrade: BookGrade[] = [
  {
    grade: 9,
    accent: "from-emerald-500 to-teal-500",
    description: "Foundation textbooks for lower secondary study with direct local PDF access.",
    subjects: [
      {
        name: "Amharic",
        description: "Amharic textbook for Grade 9 with 175 and a local PDF copy inside the app.",
        pages: "175",
        size: "18 MB",
        image: "/books/covers/grade-9-amharic.png",
        pdf: "/books/pdfs/grade-9-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Biology textbook for Grade 9 with 171 and a local PDF copy inside the app.",
        pages: "171",
        size: "11 MB",
        image: "/books/covers/grade-9-biology.png",
        pdf: "/books/pdfs/grade-9-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Chemistry textbook for Grade 9 with 183 and a local PDF copy inside the app.",
        pages: "183",
        size: "8 MB",
        image: "/books/covers/grade-9-chemistry.png",
        pdf: "/books/pdfs/grade-9-chemistry.pdf",
      },
      {
        name: "Citizenship Education",
        description: "Citizenship Education textbook for Grade 9 with 173 and a local PDF copy inside the app.",
        pages: "173",
        size: "7 MB",
        image: "/books/covers/grade-9-citizenship-education.png",
        pdf: "/books/pdfs/grade-9-citizenship-education.pdf",
      },
      {
        name: "Economics",
        description: "Economics textbook for Grade 9 with 119 and a local PDF copy inside the app.",
        pages: "119",
        size: "5 MB",
        image: "/books/covers/grade-9-economics.png",
        pdf: "/books/pdfs/grade-9-economics.pdf",
      },
      {
        name: "English",
        description: "English textbook for Grade 9 with 237 and a local PDF copy inside the app.",
        pages: "237",
        size: "78 MB",
        image: "/books/covers/grade-9-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-9-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Geography textbook for Grade 9 with 237 and a local PDF copy inside the app.",
        pages: "237",
        size: "22 MB",
        image: "/books/covers/grade-9-geography.png",
        pdf: "/books/pdfs/grade-9-geography.pdf",
      },
      {
        name: "Health And Physical Education Hpe",
        description: "Health And Physical Education Hpe textbook for Grade 9 with 167 and a local PDF copy inside the app.",
        pages: "167",
        size: "7 MB",
        image: "/books/covers/grade-9-health-and-physical-education-hpe.png",
        pdf: "/books/pdfs/grade-9-health-and-physical-education-hpe.pdf",
      },
      {
        name: "History",
        description: "History textbook for Grade 9 with 219 and a local PDF copy inside the app.",
        pages: "219",
        size: "10 MB",
        image: "/books/covers/grade-9-history.png",
        pdf: "/books/pdfs/grade-9-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Information Technology textbook for Grade 9 with 251 and a local PDF copy inside the app.",
        pages: "251",
        size: "14 MB",
        image: "/books/covers/grade-9-information-technology.png",
        pdf: "/books/pdfs/grade-9-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Mathematics textbook for Grade 9 with 375 and a local PDF copy inside the app.",
        pages: "375",
        size: "18 MB",
        image: "/books/covers/grade-9-mathematics.png",
        pdf: "/books/pdfs/grade-9-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Physics textbook for Grade 9 with 183 and a local PDF copy inside the app.",
        pages: "183",
        size: "8 MB",
        image: "/books/covers/grade-9-physics.png",
        pdf: "/books/pdfs/grade-9-physics.pdf",
      }
    ],
  },
  {
    grade: 10,
    accent: "from-sky-500 to-cyan-500",
    description: "Grade 10 textbooks for stronger subject mastery and exam preparation.",
    subjects: [
      {
        name: "Amharic",
        description: "Amharic textbook for Grade 10 with 164 and a local PDF copy inside the app.",
        pages: "164",
        size: "16 MB",
        image: "/books/covers/grade-10-amharic.png",
        pdf: "/books/pdfs/grade-10-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Biology textbook for Grade 10 with 182 and a local PDF copy inside the app.",
        pages: "182",
        size: "12 MB",
        image: "/books/covers/grade-10-biology.png",
        pdf: "/books/pdfs/grade-10-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Chemistry textbook for Grade 10 with 306 and a local PDF copy inside the app.",
        pages: "306",
        size: "7 MB",
        image: "/books/covers/grade-10-chemistry.png",
        pdf: "/books/pdfs/grade-10-chemistry.pdf",
      },
      {
        name: "Citizenship Education",
        description: "Citizenship Education textbook for Grade 10 with 202 and a local PDF copy inside the app.",
        pages: "202",
        size: "12 MB",
        image: "/books/covers/grade-10-citizenship-education.png",
        pdf: "/books/pdfs/grade-10-citizenship-education.pdf",
      },
      {
        name: "Economics",
        description: "Economics textbook for Grade 10 with 190 and a local PDF copy inside the app.",
        pages: "190",
        size: "5 MB",
        image: "/books/covers/grade-10-economics.png",
        pdf: "/books/pdfs/grade-10-economics.pdf",
      },
      {
        name: "English",
        description: "English textbook for Grade 10 with 326 and a local PDF copy inside the app.",
        pages: "326",
        size: "7 MB",
        image: "/books/covers/grade-10-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-10-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Geography textbook for Grade 10 with 214 and a local PDF copy inside the app.",
        pages: "214",
        size: "12 MB",
        image: "/books/covers/grade-10-geography.png",
        pdf: "/books/pdfs/grade-10-geography.pdf",
      },
      {
        name: "Health And Physical Education Hpe",
        description: "Health And Physical Education Hpe textbook for Grade 10 with 158 and a local PDF copy inside the app.",
        pages: "158",
        size: "10 MB",
        image: "/books/covers/grade-10-health-and-physical-education-hpe.png",
        pdf: "/books/pdfs/grade-10-health-and-physical-education-hpe.pdf",
      },
      {
        name: "History",
        description: "History textbook for Grade 10 with 246 and a local PDF copy inside the app.",
        pages: "246",
        size: "12 MB",
        image: "/books/covers/grade-10-history.png",
        pdf: "/books/pdfs/grade-10-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Information Technology textbook for Grade 10 with 234 and a local PDF copy inside the app.",
        pages: "234",
        size: "12 MB",
        image: "/books/covers/grade-10-information-technology.png",
        pdf: "/books/pdfs/grade-10-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Mathematics textbook for Grade 10 with 394 and a local PDF copy inside the app.",
        pages: "394",
        size: "20 MB",
        image: "/books/covers/grade-10-mathematics.png",
        pdf: "/books/pdfs/grade-10-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Physics textbook for Grade 10 with 258 and a local PDF copy inside the app.",
        pages: "258",
        size: "10 MB",
        image: "/books/covers/grade-10-physics.png",
        pdf: "/books/pdfs/grade-10-physics.pdf",
      }
    ],
  },
  {
    grade: 11,
    accent: "from-violet-500 to-fuchsia-500",
    description: "Upper-secondary textbooks for deeper science, social science, and language study.",
    subjects: [
      {
        name: "Agriculture",
        description: "Agriculture textbook for Grade 11 with 270 and a local PDF copy inside the app.",
        pages: "270",
        size: "22 MB",
        image: "/books/covers/grade-11-agriculture.png",
        pdf: "/books/pdfs/grade-11-agriculture.pdf",
      },
      {
        name: "Amharic",
        description: "Amharic textbook for Grade 11 with 216 and a local PDF copy inside the app.",
        pages: "216",
        size: "4 MB",
        image: "/books/covers/grade-11-amharic.png",
        pdf: "/books/pdfs/grade-11-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Biology textbook for Grade 11 with 294 and a local PDF copy inside the app.",
        pages: "294",
        size: "38 MB",
        image: "/books/covers/grade-11-biology.png",
        pdf: "/books/pdfs/grade-11-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Chemistry textbook for Grade 11 with 342 and a local PDF copy inside the app.",
        pages: "342",
        size: "10 MB",
        image: "/books/covers/grade-11-chemistry.png",
        pdf: "/books/pdfs/grade-11-chemistry.pdf",
      },
      {
        name: "Economics",
        description: "Economics textbook for Grade 11 with 202 and a local PDF copy inside the app.",
        pages: "202",
        size: "7 MB",
        image: "/books/covers/grade-11-economics.png",
        pdf: "/books/pdfs/grade-11-economics.pdf",
      },
      {
        name: "English",
        description: "English textbook for Grade 11 with 290 and a local PDF copy inside the app.",
        pages: "290",
        size: "143 MB",
        image: "/books/covers/grade-11-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-11-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Geography textbook for Grade 11 with 254 and a local PDF copy inside the app.",
        pages: "254",
        size: "11 MB",
        image: "/books/covers/grade-11-geography.png",
        pdf: "/books/pdfs/grade-11-geography.pdf",
      },
      {
        name: "History",
        description: "History textbook for Grade 11 with 270 and a local PDF copy inside the app.",
        pages: "270",
        size: "12 MB",
        image: "/books/covers/grade-11-history.png",
        pdf: "/books/pdfs/grade-11-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Information Technology textbook for Grade 11 with 170 and a local PDF copy inside the app.",
        pages: "170",
        size: "5 MB",
        image: "/books/covers/grade-11-information-technology.png",
        pdf: "/books/pdfs/grade-11-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Mathematics textbook for Grade 11 with 494 and a local PDF copy inside the app.",
        pages: "494",
        size: "137 MB",
        image: "/books/covers/grade-11-mathematics.png",
        pdf: "/books/pdfs/grade-11-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Physics textbook for Grade 11 with 338 and a local PDF copy inside the app.",
        pages: "338",
        size: "11 MB",
        image: "/books/covers/grade-11-physics.png",
        pdf: "/books/pdfs/grade-11-physics.pdf",
      }
    ],
  },
  {
    grade: 12,
    accent: "from-amber-400 to-orange-500",
    description: "Final-year textbooks with local previews and direct downloads for revision.",
    subjects: [
      {
        name: "Agriculture",
        description: "Agriculture textbook for Grade 12 with 302 and a local PDF copy inside the app.",
        pages: "302",
        size: "40 MB",
        image: "/books/covers/grade-12-agriculure.png",
        pdf: "/books/pdfs/grade-12-agriculure.pdf",
      },
      {
        name: "Amharic",
        description: "Amharic textbook for Grade 12 with 217 and a local PDF copy inside the app.",
        pages: "217",
        size: "4.4 MB",
        image: "/books/covers/grade-12-amharic.png",
        pdf: "/books/pdfs/grade-12-amharic.pdf",
      },
      {
        name: "Biology",
        description: "Biology textbook for Grade 12 with 358 and a local PDF copy inside the app.",
        pages: "358",
        size: "172 MB",
        image: "/books/covers/grade-12-biology.png",
        pdf: "/books/pdfs/grade-12-biology.pdf",
      },
      {
        name: "Chemistry",
        description: "Chemistry textbook for Grade 12 with 298 and a local PDF copy inside the app.",
        pages: "298",
        size: "8.8 MB",
        image: "/books/covers/grade-12-chemistry.png",
        pdf: "/books/pdfs/grade-12-chemistry.pdf",
      },
      {
        name: "Economics",
        description: "Economics textbook for Grade 12 with 214 and a local PDF copy inside the app.",
        pages: "214",
        size: "5 MB",
        image: "/books/covers/grade-12-economics.png",
        pdf: "/books/pdfs/grade-12-economics.pdf",
      },
      {
        name: "English",
        description: "English textbook for Grade 12 with 270 and a local PDF copy inside the app.",
        pages: "270",
        size: "15 MB",
        image: "/books/covers/grade-12-english-for-ethiopia.png",
        pdf: "/books/pdfs/grade-12-english-for-ethiopia.pdf",
      },
      {
        name: "Geography",
        description: "Geography textbook for Grade 12 with 266 and a local PDF copy inside the app.",
        pages: "266",
        size: "10 MB",
        image: "/books/covers/grade-12-geography.png",
        pdf: "/books/pdfs/grade-12-geography.pdf",
      },
      {
        name: "History",
        description: "History textbook for Grade 12 with 290 and a local PDF copy inside the app.",
        pages: "290",
        size: "8 MB",
        image: "/books/covers/grade-12-history.png",
        pdf: "/books/pdfs/grade-12-history.pdf",
      },
      {
        name: "Information Technology",
        description: "Information Technology textbook for Grade 12 with 210 and a local PDF copy inside the app.",
        pages: "210",
        size: "10 MB",
        image: "/books/covers/grade-12-information-technology.png",
        pdf: "/books/pdfs/grade-12-information-technology.pdf",
      },
      {
        name: "Mathematics",
        description: "Mathematics textbook for Grade 12 with 426 and a local PDF copy inside the app.",
        pages: "426",
        size: "117 MB",
        image: "/books/covers/grade-12-mathematics.png",
        pdf: "/books/pdfs/grade-12-mathematics.pdf",
      },
      {
        name: "Physics",
        description: "Physics textbook for Grade 12 with 186 and a local PDF copy inside the app.",
        pages: "186",
        size: "11 MB",
        image: "/books/covers/grade-12-physics.png",
        pdf: "/books/pdfs/grade-12-physics.pdf",
      }
    ],
  }
];

export const getBooksGrade = (grade: number) =>
  booksByGrade.find((item) => item.grade === grade);
